# SPDX-License-Identifier: MIT
---
galaxy_info:
  author: adicrescenzo
  description: "Configure existing LXC containers on Proxmox to run Proxmox Backup Server"
  license: "MIT"
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - proxmox
    - lxc
    - pbs
    - backup
    - container

dependencies: []
