name: Test Collection

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: ['2.12', '2.13', '2.14', 'latest']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.ansible-version }}" == "latest" ]; then
            pip install ansible
          else
            pip install ansible-core~=${{ matrix.ansible-version }}.0
          fi

      - name: Install collection dependencies
        run: |
          ansible-galaxy collection install community.general

      - name: Validate collection build
        run: |
          ansible-galaxy collection build --force

      - name: Install built collection
        run: |
          ansible-galaxy collection install *.tar.gz --force

      - name: Test collection import
        run: |
          ansible-doc adicrescenzo.proxmox_backup_server_lxc.lxc_setup || true
          ansible-doc adicrescenzo.proxmox_backup_server_lxc.pbs_setup || true

      - name: Syntax check playbooks
        run: |
          if [ -d "playbooks" ]; then
            for playbook in playbooks/*.yml; do
              if [ -f "$playbook" ]; then
                echo "Checking syntax of $playbook"
                ansible-playbook --syntax-check "$playbook"
              fi
            done
          fi

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Lint Ansible content
        run: |
          ansible-lint